export ALPINE_VERSION=3.5.1
export ETCD_VERSION=v3
export HTTP_ECHO_VERSION=v1
export JAMESD_VERSION=v2
export JWTD_VERSION=v1
export MONGODB_VERSION=1.0.0 #custom!
export SKYDNS_VERSION=2.0.0 #custom!
export SKYDNS_POD_ANNOUNCER_VERSION=v1
